### ISSUE TITLE
Remember Settings

### ISSUE THREAD

**Issue by GirkovArpa** [GirkovArpa/crossover-lite#3]
> @GirkovArpa,
> The crossover-lite is in some ways a fantastic application.  :up:
> 
> But in every day life it is missing at least one important feature: Remember my favorite theme.
> 
> The default theme, with a feather, will never be the one that is needed for the job - and it's simply too disappointing to have to navigate for a usable theme, everytime I launche the program!
> 
> Any chance it will be updated?  :tellme:
- https://www.donationcoder.com/forum/index.php?topic=18632.msg445190#msg445190

**Comment by MustafaHi** [comment]
### Solved by [v0.1.2](https://github.com/GirkovArpa/crossover-lite/tree/v0.1.2)
